Petit-happy/record-factory

app/controllers/admin/product_controller.rb
app/controllers/arrivals_controller.rb
app/views/arrivals/top.html.erb
app/views/devise/sessions/new.html.erb
config/routes.rb
db/seeds.rb
test/fixtures/arrivals.yml

admin_signin

---

app/views/end_user/products/index.html.erb
config/routes.rb

modify_productview&routes

---

app/assets/stylesheets/application.scss
app/controllers/application_controller.rb
app/views/layouts/application.html.erb
app/views/shared/_admin_header.html.erb
app/views/shared/_footer.html.erb

partial header and footer

---

app/controllers/end_user/products_controller.rb
app/views/end_user/products/show.html.erb
db/seeds.rb

[create]EndUserseed

---

app/assets/stylesheets/application.scss
app/controllers/admin/end_users_controller.rb
app/views/admin/end_users/index.html.erb
app/views/admin/end_users/top.html.erb
app/views/shared/_admin_header.html.erb

管理者画面内にて、会員ユーザーの一覧画面を作成。
状況に応じて逐次変更していきます。

placed admin end user index

---

db/seeds.rb

E products2

---

db/seeds.rb

modify_seed

---

app/controllers/genres_controller.rb
app/models/artist.rb
app/models/genre.rb
app/models/label.rb
app/models/product.rb
app/views/end_user/products/show.html.erb

E product3

---

app/controllers/admin/end_users_controller.rb
app/views/admin/end_users/edit.html.erb
app/views/admin/end_users/index.html.erb
app/views/admin/end_users/show.html.erb
app/views/shared/_admin_header.html.erb

Admin user show

---

app/controllers/admin/end_users_controller.rb
app/controllers/end_user/products_controller.rb
app/models/artist.rb
app/models/genre.rb
app/models/label.rb
app/views/admin/end_users/show.html.erb
app/views/end_user/products/show.html.erb
config/routes.rb
db/schema.rb
db/seeds.rb

E product4

---

app/views/admin/end_users/edit.html.erb
app/views/admin/end_users/index.html.erb
app/views/admin/end_users/show.html.erb

lillte change with bootstrap at show, index and edit of admin-end_user

---

app/assets/stylesheets/application.scss
app/controllers/admin/orders_controller.rb
app/models/order.rb
app/views/admin/end_users/show.html.erb
app/views/admin/orders/show.html.erb
app/views/shared/_admin_header.html.erb

Admin order show

---

app/controllers/admin/orders_controller.rb
app/views/admin/orders/show.html.erb

almost done admin order show

---

app/controllers/admin/products_controller.rb
app/models/order_detail.rb
app/views/admin/products/index.html.erb
app/views/admin/products/show.html.erb

branch change

---

app/controllers/admin/orders_controller.rb
app/controllers/admin/products_controller.rb
app/views/admin/products/show.html.erb

Admin product index

---

app/assets/stylesheets/application.scss
app/controllers/admin/products_controller.rb
app/views/admin/arrivals/new.html.erb
app/views/admin/orders/index.html.erb
app/views/admin/products/edit.html.erb
app/views/admin/products/show.html.erb

商品の編集画面実装
ディスクの内容編集部分が未実装なのと、
商品情報を編集しても反映されないのは今後やります。

Product edit

---

app/controllers/admin/products_controller.rb
app/models/product.rb
app/views/admin/products/edit.html.erb
app/views/admin/products/index.html.erb
app/views/admin/products/show.html.erb

search of product index

---

app/assets/stylesheets/application.scss
app/controllers/artists_controller.rb
app/controllers/genres_controller.rb
app/controllers/labels_controller.rb
app/views/admin/end_users/index.html.erb
app/views/admin/orders/index.html.erb
app/views/artists/index.html.erb
app/views/genres/index.html.erb
app/views/labels/index.html.erb
app/views/labels/new.html.erb
app/views/shared/_admin_header.html.erb

finished setting

---

app/models/arrival.rb
app/models/end_user.rb
app/models/order.rb
app/models/product.rb
app/models/song.rb
app/views/admin/arrivals/new.html.erb
app/views/admin/end_users/edit.html.erb
app/views/admin/products/edit.html.erb
app/views/shared/_error.html.erb

middle of validation

---

app/assets/stylesheets/application.scss
app/controllers/admin/arrivals_controller.rb
app/controllers/admin/end_users_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/admin/products_controller.rb
app/models/product.rb
app/views/admin/arrivals/_arrival.json.jbuilder
app/views/admin/arrivals/new.html.erb
app/views/admin/arrivals/show.html.erb
app/views/admin/arrivals/top.html.erb
app/views/admin/artists/index.html.erb
app/views/admin/end_users/edit.html.erb
app/views/admin/end_users/index.html.erb
app/views/admin/end_users/show.html.erb
app/views/admin/genres/index.html.erb
app/views/admin/labels/index.html.erb
app/views/admin/orders/index.html.erb
app/views/admin/orders/show.html.erb
app/views/admin/products/edit.html.erb
app/views/admin/products/index.html.erb
app/views/admin/products/new.html.erb
app/views/admin/products/show.html.erb
app/views/admin_users/sessions/new.html.erb
app/views/end_user/products/show.html.erb
app/views/layouts/application.html.erb
app/views/shared/_admin_header.html.erb
app/views/shared/_footer.html.erb
config/routes.rb

Admin namespace

---

app/controllers/end_user/cart_items_controller.rb
app/controllers/end_user/orders_controller.rb
app/views/end_user/cart_items/confirmation.html.erb
app/views/end_user/cart_items/index.html.erb

Confirmation3

---

app/assets/stylesheets/application.scss
app/controllers/admin/end_users_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/admin/products_controller.rb
app/models/end_user.rb
app/models/product.rb
app/views/admin/orders/show.html.erb

finished paranoia

---

app/assets/stylesheets/application.scss
app/controllers/end_user/cart_items_controller.rb
app/models/product.rb
app/views/end_user/products/show.html.erb

カートの個数をストックで可変的にする

---

.rspec
Gemfile
Gemfile.lock
config/application.rb
spec/admin/end_user_spec.rb
spec/admin/product_spec.rb
spec/end_user/end_user_spec.rb
spec/end_user/order_spec.rb
spec/end_user/product_spec.rb

created test files
